quarkus.package.jar.type=uber-jar


quarkus.security.users.embedded.enabled=true
quarkus.security.users.embedded.plain-text=true
quarkus.security.users.embedded.users.hawtio=s3cr3t!
quarkus.security.users.embedded.roles.hawtio=admin

quarkus.camel.jolokia.register-management-endpoint=true
quarkus.log.level=INFO


quarkus.devservices.enabled=false
quarkus.management.enabled=true


topic=my-topic
#broker=my-cluster-kafka-bootstrap.strimzi-kafka.svc.cluster.local:9093
broker=my-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092

quarkus.datasource.db-kind=mysql
quarkus.datasource.username=mysqluser
quarkus.datasource.password=mysqlpw
quarkus.datasource.jdbc.url=jdbc:mysql://mysql.kafka.svc.cluster.local:3306/inventory


