quarkus.package.jar.type=uber-jar


quarkus.security.users.embedded.enabled=true
quarkus.security.users.embedded.plain-text=true
quarkus.security.users.embedded.users.hawtio=s3cr3t!
quarkus.security.users.embedded.roles.hawtio=admin

